// <auto-generated />
namespace DocumentEditor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IntialDocumentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialDocumentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121840427_IntialDocumentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
